import { EffectSchema, BLEND_MODES } from "@/types";

export const LOCAL_SCHEMAS: EffectSchema[] = [
    {
        type: "ASCII",
        label: "ASCII Art",
        description: "Render the image as ASCII characters mapped to luminance.",
        params: {
            "size": "int 4-300 - cell size in px",
            "mapping": "Brightness | Random — character selection",
            "f_col": "str - font color (hex)",
            "bg_mode": "Fixed Color | Sample Image",
            "bg_col": "color - background hex if Fixed Color",
            "soft_mask": "bool - softly mask drawing with luminance",
            "set": "HRDWRE | HACKER | Standard | Blocky | Matrix",
            "ox": "int - horizontal character offset",
            "oy": "int - vertical character offset",
            "range": "int 0-255 - mask threshold range",
            "blend": `str - blend mode: ${BLEND_MODES.join(", ")}`,
        },
    },
    {
        type: "DITHER",
        label: "Dither",
        description: "Apply pixel dithering using classic or error-diffusion patterns.",
        params: {
            "size": "int 1-200 - dither cell size",
            "col": "str - dither color (hex)",
            "pattern": "Classic 2x2 | Fine Grid | Floyd-Steinberg | Atkinson | Random",
            "range": "int 0-255 - mask threshold range",
            "blend": `str - blend mode: ${BLEND_MODES.join(", ")}`,
        },
    },
    {
        type: "GLITCH",
        label: "JPEG Glitch",
        description: "Corrupt JPEG data to create digital glitch artifacts.",
        params: {
            "amount": "int 1-250 - corruption passes",
            "quality": "int 1-100 - JPEG encode quality (lower = more artifacts)",
            "range": "int 0-255 - mask threshold range",
            "blend": `str - blend mode: ${BLEND_MODES.join(", ")}`,
        },
    },
    {
        type: "EDGE",
        label: "Edge Detect",
        description: "Detect edges with Sobel operators and render as line art.",
        params: {
            "sensitivity": "int 0-100 - edge sensitivity",
            "thickness": "int 1-10 - edge thickness",
            "color": "str - line color hex",
            "range": "int 0-255 - mask threshold range",
            "blend": `str - blend mode: ${BLEND_MODES.join(", ")}`,
        },
    },
    {
        type: "SOURCE",
        label: "Source Image",
        description: "Inject the original source image into the layer stack.",
        params: {
            "mosaic": "int 1-100 - mosaic pixel size",
            "opacity": "float 0-1 - layer transparency",
            "blend": `str - blend mode: ${BLEND_MODES.join(", ")}`,
        },
    },
    {
        type: "CRT",
        label: "CRT Scanlines",
        description: "Simulate a CRT monitor with scanlines and color tinting.",
        params: {
            "col": "str - tint color (hex)",
            "intensity": "int 0-255 - scanline darkness",
            "freq": "int 1-100 - scanline frequency",
            "oy": "int 0-50 - wave amplitude",
            "top": "int 0-100 - top/bottom vignette strength",
            "range": "int 0-255 - mask threshold range",
            "blend": `str - blend mode: ${BLEND_MODES.join(", ")}`,
        },
    },
    {
        type: "PIXEL_SORT",
        label: "Pixel Sort",
        description: "Sort pixels within masked segments by luminance.",
        params: {
            "direction": "Horizontal | Vertical",
            "sort_by": "Brightness | Hue | Saturation — sorting property",
            "reverse": "bool - sort descending",
            "min_len": "int 0-2000 - minimum segment length",
            "max_len": "int 0-10000 - maximum segment length",
            "randomness": "float 0.0-1.0 - sort randomness",
            "range": "int 0-255 - mask threshold range",
            "blend": `str - blend mode: ${BLEND_MODES.join(", ")}`,
        },
    },
    {
        type: "BLOCK_GLITCH",
        label: "Block Glitch",
        description: "Randomly shifts blocks of the image based on intensity and mask.",
        params: {
            "size": "int 1-256 - square block dimensions",
            "amount": "float 0-1 - glitch probability per block",
            "seed": "int - random variation seed",
            "range": "int 0-255 - mask threshold range",
            "blend": `str - blend mode: ${BLEND_MODES.join(", ")}`,
        },
    },
    {
        type: "NOISE",
        label: "Noise / VHS",
        description: "Add digital grain or VHS-style analog interference lines.",
        params: {
            "amount": "float 0-1 - noise intensity",
            "noise_type": "Uniform | Gaussian | VHS — flavor of noise",
            "seed": "int - random seed",
            "range": "int 0-255 - mask threshold range",
            "blend": `str - blend mode: ${BLEND_MODES.join(", ")}`,
        },
    },
    {
        type: "HALFTONE",
        label: "Halftone",
        description: "Classic print-style dot screen based on luminance.",
        params: {
            "size": "int 2-100 - dot spacing",
            "method": "Classic - raster method",
            "col": "str - dot color (hex)",
            "dot_scale": "float 0.1-1.5 - dot size multiplier",
            "range": "int 0-255 - mask threshold range",
            "blend": `str - blend mode: ${BLEND_MODES.join(", ")}`,
        },
    },
    {
        type: "POSTERIZE",
        label: "Posterize",
        description: "Reduce color depth for a retro, quantized style.",
        params: {
            "levels": "int 1-8 - bit depth (1=extreme 1-bit, 8=original 8-bit)",
            "range": "int 0-255 - mask threshold range",
            "blend": `str - blend mode: ${BLEND_MODES.join(", ")}`,
        },
    },
    {
        type: "GRADIENT_MAP",
        label: "Gradient Map",
        description: "Map image luminance to a 2-4 stop color gradient.",
        params: {
            "num_colors": "2 | 4 - stop count",
            "col0": "color - stop 0 color",
            "pos0": "int 0-255 - stop 0 position",
            "col1": "color - stop 1 color",
            "pos1": "int 0-255 - stop 1 position",
            "col2": "color - stop 2 color",
            "pos2": "int 0-255 - stop 2 position",
            "col3": "color - stop 3 color",
            "pos3": "int 0-255 - stop 3 position",
            "range": "int 0-255 - mask threshold range",
            "blend": `str - blend mode: ${BLEND_MODES.join(", ")}`,
        },
    },
    {
        type: "LEVELS",
        label: "Levels",
        description: "Adjust blacks, midtones (gamma), and highlights.",
        params: {
            "black_lift": "int 0-255 - lift black level",
            "mid_point": "float 0.1-5.0 - gamma midpoint",
            "white_point": "int 0-255 - highlight clip level",
            "range": "int 0-255 - mask threshold range",
            "blend": `str - blend mode: ${BLEND_MODES.join(", ")}`,
        },
    },
    {
        type: "THRESHOLD",
        label: "Threshold",
        description: "Hard black/white cut at a specific luminance.",
        params: {
            "threshold_val": "int 0-255 - luminance threshold",
            "range": "int 0-255 - mask threshold range",
            "blend": `str - blend mode: ${BLEND_MODES.join(", ")}`,
        },
    },
    {
        type: "TEXTURE",
        label: "Texture Source",
        description: "Upload and overlay a custom texture or image layer.",
        params: {
            "invert": "bool - invert texture colors",
            "scale": "float 0.1-5.0 - texture scale multiplier",
            "rotation": "int -180-180 - texture rotation in degrees",
            "ox": "int - horizontal offset",
            "oy": "int - vertical offset",
            "repeat": "bool - repeat/tile texture",
            "luma_alpha": "bool - use luminance as opacity",
            "range": "int 0-255 - mask threshold range",
            "blend": `str - blend mode: ${BLEND_MODES.join(", ")}`,
        },
    },
    {
        type: "TILESET_DITHER",
        label: "Tileset Dither",
        description: "Hardware-style dither using symbols and optional Harmony.",
        params: {
            "size": "int 2-500 - tile size",
            "mode": "Source Colors | Harmony",
            "full_bg": "bool - background on/off",
            "symbol_set": "standard | minimal | binary | hardware | organic | braille | circuit | angles",
            "brightness": "float 0.1-4.0",
            "contrast": "float 0.1-4.0",
            "num_colors": "4",
            "col0": "color - palette 0",
            "col1": "color - palette 1",
            "col2": "color - palette 2",
            "col3": "color - palette 3",
            "range": "int 0-255 - mask threshold range",
            "blend": `str - blend mode: ${BLEND_MODES.join(", ")}`,
        },
    }
];
